-   id: check-commit-message-format
    name: Check commit message format
    description: Checks that commit message begin with a proper prefix
    entry: check-commit-message-format
    language: python
    stages: [commit, push, manual]
