- id: check-commit-message-format
  name: check commit message format
  description: >
    Checks that commit message begin with a proper prefix followeded
    by a space before the message body.  This ensures standards in 
    commit and message types and provides a foundation for semantic-release
    to auto increment releases.
  entry: check-commit-message-format
  language: python
  language_version: python3
  minimum_pre_commit_version: "2.21"
